version: '3'

# networks:
#     default:
#         external:
#             name:webapp

volumes:
    volgusmysql2:

services:
    nginx_livewire:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        restart: always
        ports:
            - '81:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:rw
        depends_on:
            - php_livewire
            - mysql_livewire

    php_livewire:
        build:
            context: ./docker
            dockerfile: php.dockerfile
        image: voipgus/meuphp
        restart: always
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html

    mysql_livewire:
        image: mysql:8.0
        container_name: ${APP_NAME}_mysql
        restart: always
        tty: true
        volumes:
            - volgusmysql2:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            # MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}


